### ISSUE TITLE
홈페이지 > 도우미 수정

### ISSUE THREAD

**Issue by kino-ona** [kino-ona/amway_morning#1]
홈페이지 > 도우미 
첫번째 Step 01 주석처리

**Comment by ona-yoonhee** [comment]
확인 했습니다 ~

**Comment by ona-yoonhee** [comment]
@ona-hyejinkim  이렇게하면 알람이 가나요...?

**Comment by kino-ona** [comment]
@ona-yoonhee  메일로 들어옴 이거는 깃헙데스크탑 처럼 뭐 앱이 없나 메일 알림 말고
